In [5]:
#### NUMPY ASSIGNMENT
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
for i in range(5):
    print(type(list_[i]))
    print(type(array_list[i]))

<class 'str'>
<class 'numpy.str_'>
<class 'str'>
<class 'numpy.str_'>
<class 'str'>
<class 'numpy.str_'>
<class 'str'>
<class 'numpy.str_'>
<class 'str'>
<class 'numpy.str_'>


In [10]:
array_list = np.array(list_, dtype = int)
array_list

array([1, 2, 3, 4, 5])

In [11]:
for i in range(5):
    print(type(list_[i]))
    print(type(array_list[i]))

<class 'str'>
<class 'numpy.int32'>
<class 'str'>
<class 'numpy.int32'>
<class 'str'>
<class 'numpy.int32'>
<class 'str'>
<class 'numpy.int32'>
<class 'str'>
<class 'numpy.int32'>


In [14]:
num_list = [[1,2,3],[4,5,6]]
num_array = np.array(num_list)
num_array.shape

(2, 3)

In [15]:
num_array.size

6

In [25]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])